In [1]:
#Problem Statement : Hospital Patient Data Analysis
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [2]:
df=pd.read_csv('Patient_Data.csv')
df

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45
5,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PatientID       6 non-null      int64
 1   Name            6 non-null      object
 2   Department      6 non-null      object
 3   Doctor          6 non-null      object
 4   BillAmount      4 non-null      float64
 5   ReceptionistID  6 non-null      int64
 6   CheckInTime     6 non-null      object
dtypes: float64(1), int64(2), object(4)
memory usage: 468.0+ bytes

In [4]:
df[['PatientID','Department','Doctor','BillAmount']]

   PatientID   Department     Doctor  BillAmount
0        101   Cardiology  Dr. Smith      5000.0
1        102    Neurology   Dr. John         NaN
2        103  Orthopedics    Dr. Lee      7500.0
3        104   Cardiology  Dr. Smith      6200.0
4        105  Dermatology   Dr. Rose         NaN
5        101   Cardiology  Dr. Smith      5000.0

In [6]:
df.drop(columns=['ReceptionistID','CheckInTime'],inplace=True)
df.head()

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN

In [11]:
df.duplicated().sum()

np.int64(1)

In [12]:
df=df.drop_duplicates()

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
df['BillAmount']=df['BillAmount'].fillna(df['BillAmount'].mean())
df

   PatientID     Name   Department     Doctor   BillAmount
0        101    Alice   Cardiology  Dr. Smith  5000.000000
1        102      Bob    Neurology   Dr. John  6233.333333
2        103  Charlie  Orthopedics    Dr. Lee  7500.000000
3        104    David   Cardiology  Dr. Smith  6200.000000
4        105      Eva  Dermatology   Dr. Rose  6233.333333

In [18]:
df.groupby(['Department' , 'BillAmount']).sum()

                         PatientID     Name     Doctor
Department  BillAmount
Cardiology  5000.000000        101    Alice  Dr. Smith
            6200.000000        104    David  Dr. Smith
Dermatology 6233.333333        105      Eva   Dr. Rose
Neurology   6233.333333        102      Bob   Dr. John
Orthopedics 7500.000000        103  Charlie    Dr. Lee

In [19]:
df1=pd.read_csv('Billing_Data.csv')
df

   PatientID     Name   Department     Doctor   BillAmount
0        101    Alice   Cardiology  Dr. Smith  5000.000000
1        102      Bob    Neurology   Dr. John  6233.333333
2        103  Charlie  Orthopedics    Dr. Lee  7500.000000
3        104    David   Cardiology  Dr. Smith  6200.000000
4        105      Eva  Dermatology   Dr. Rose  6233.333333

In [25]:
df2=pd.merge(df,df1)
df2

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,2000,3000
1,102,Bob,Neurology,Dr. John,6233.333333,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.000000,3000,3200
4,105,Eva,Dermatology,Dr. Rose,6233.333333,1000,4000

In [26]:
df['Department'].value_counts()

Department
Cardiology     2
Neurology      1
Orthopedics    1
Dermatology    1
Name: count, dtype: int64

In [29]:
new_patients=pd.DataFrame({'PatientID':[106,107,108],
                          'Name':['Tom','Zen','sadie'],
                          'Department':['Cardiology','Neurology','Orthopedics'],
                          'Doctor':['A','B','c'],
                          'BillAmount':[5000,6000,3000],
                          'InsuranceCovered':[1000,2000,1500],
                          'FinalAmount':[3000,3500,3800]})
new_patients

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,106,Tom,Cardiology,A,5000,1000,3000
1,107,Zen,Neurology,B,6000,2000,3500
2,108,sadie,Orthopedics,c,3000,1500,3800

In [31]:
df3=pd.concat([df2,new_patients],ignore_index=True)
df3

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,2000,3000
1,102,Bob,Neurology,Dr. John,6233.333333,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.000000,3000,3200
4,105,Eva,Dermatology,Dr. Rose,6233.333333,1000,4000
5,106,Tom,Cardiology,A,5000.000000,1000,3000
6,107,Zen,Neurology,B,6000.000000,2000,3500
7,108,sadie,Orthopedics,c,3000.000000,1500,3800

In [32]:
Billing_cat=pd.DataFrame({'InsuranceCovered':[500,800],
              'FinalAmount':[2500,3000]})
Billing_cat

   InsuranceCovered  FinalAmount
0               500         2500
1               800         3000

In [34]:
df4=pd.concat([df3,Billing_cat],ignore_index=True)
df4

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101.0,Alice,Cardiology,Dr. Smith,5000.000000,2000,3000
1,102.0,Bob,Neurology,Dr. John,6233.333333,1500,3500
2,103.0,Charlie,Orthopedics,Dr. Lee,7500.000000,2500,5000
3,104.0,David,Cardiology,Dr. Smith,6200.000000,3000,3200
4,105.0,Eva,Dermatology,Dr. Rose,6233.333333,1000,4000
5,106.0,Tom,Cardiology,A,5000.000000,1000,3000
6,107.0,Zen,Neurology,B,6000.000000,2000,3500
7,108.0,sadie,Orthopedics,c,3000.000000,1500,3800
8,NaN,NaN,NaN,NaN,NaN,500,2500
9,NaN,NaN,NaN,NaN,NaN,800,3000